### ISSUE TITLE
Running 'apm install' in cloned repo does not seem to install any package

### ISSUE THREAD

**Issue by grempe** [avh4/atom-elm-format#2]
I followed the instructions for install found here (why not also in the README for this repo?)

https://github.com/avh4/elm-format/blob/master/README.md

After doing so (several times, and restarting Atom), no package seems to be installed.

```
~/src/atom-elm-format (master ✔)$ apm install
Installing modules ✓

~/src/atom-elm-format (master ✔)$ ls -la /Users/glenn/.atom/packages/
total 4
drwxr-xr-x 20 glenn 680 Dec 14 12:12 .
drwxr-xr-x 14 glenn 476 Dec 12 10:32 ..
-rw-r--r--  1 glenn  60 Oct  7  2014 README.md
drwxr-xr-x 23 glenn 782 Nov 19 16:21 atom-beautify
drwxr-xr-x 10 glenn 340 Dec 12 10:30 color-picker
drwxr-xr-x 15 glenn 510 Nov 10 13:56 editorconfig
drwxr-xr-x 11 glenn 374 May 31  2015 git-log
drwxr-xr-x 13 glenn 442 May 27  2015 git-tab-status
drwxr-xr-x 10 glenn 340 May 27  2015 hex
drwxr-xr-x 16 glenn 544 Oct 31 10:13 jshint
drwxr-xr-x  7 glenn 238 Dec 12 10:30 language-docker
drwxr-xr-x  8 glenn 272 Aug 14 13:14 language-elixir
drwxr-xr-x 11 glenn 374 Nov 28 13:45 language-elm
drwxr-xr-x  8 glenn 272 Dec 12 10:30 language-haml
drwxr-xr-x 17 glenn 578 Nov 28 09:50 linter
drwxr-xr-x  8 glenn 272 Dec 14 12:12 linter-elm-make
drwxr-xr-x 12 glenn 408 Nov 10 13:57 linter-jscs
drwxr-xr-x 17 glenn 578 Nov 10 13:56 merge-conflicts
drwxr-xr-x  5 glenn 170 Oct  8  2014 tabular
drwxr-xr-x 12 glenn 408 Nov 10 13:56 wordcount
```

Atom version is 1.3.1 (latest). No elm-format menu options are present in Atom after install. Am I missing something?

**Comment by avh4** [comment]
I think I had the instructions wrong...  Try this:

``` bash
cd path/to/atom-elm-format
apm link
```

Then, in Atom:  View -> Reload

**Comment by grempe** [comment]
Yes, that worked.  I noted also that you use 'elm-format' as the menu item name and action.  All other items in that list, apparently by convention, use capitalized words.  e.g. 'Elm Format'

Does this repo become obsolete when the next version of Atom Beautify comes out with Elm support?

**Comment by grempe** [comment]
Closing as I see you updated the instructions on the elm-format repo. Thx.
